version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: sih-backend-dev
    ports:
      - "8000:8000"
    environment:
      - WHATSAPP_VERIFY_TOKEN=sih-health-chatbot-secret
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN}
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./requirements.txt
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./docker/Dockerfile.dev
        - action: sync
          path: ./
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-dev
    command: tunnel --url http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
