name: CI Pipeline

on:
  push:
    branches: [ "main", "master", "dev" ]
  pull_request:
    branches: [ "main", "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python 3.13
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8 mypy pytest pytest-asyncio httpx
          echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      # 🔹 Code Quality Checks (based on your configs)
      - name: Run Black
        run: black --check .  # uses pyproject.toml [tool.black]

      - name: Run isort
        run: isort --check-only .  # uses pyproject.toml [tool.isort]

      - name: Run Flake8
        run: flake8 .  # uses .flake8 or pyproject.toml [tool.flake8]

      - name: Run Mypy
        run: mypy src --config-file .mypy.ini

      # 🔹 Tests
      - name: Run Pytest
        run: pytest --maxfail=1 --disable-warnings -q

      # 🔹 Docker build validation
      - name: Build Docker image
        run: docker build -t sih-backend -f docker/Dockerfile .
