name: Update Contributors

on:
  schedule:
    - cron: '0 0 * * 1'  # weekly
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate contributors section
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          image_size: 80
          columns_per_row: 8
          commit_message: 'docs(readme): update contributors list'
          auto_detect_owner: true
          use_username: true
          readme_path: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
